name: Release
'on': release
jobs:
    release:
      runs-on: '${{matrix.os}}'
      strategy:
        matrix:
          os:
            - macos-11
            
      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: my-artifact
        - name: Display structure of downloaded files
          run: ls -R

        
